### ISSUE TITLE
로그인 기능 프론트 ↔ 백 연동

### ISSUE THREAD

**Issue by thelight0804** [thelight0804/subak#14]
로그인, 회원가입, 이메일 찾기, 비밀번호 찾기 기능에서 백엔드 API를 사용해서 코드 작업을 완료했습니다.
이후에 백엔드 팀원과 DB를 사용해서 테스트를 진행하면 좋을 거 같습니다.

### 회원가입
```jsx
axios.post(`http://${Config.DB_IP}/user`,{
  email: email,
  password: password,
  name: name,
  phone: phone,
}
```

### 로그인
```jsx
axios.post(`http://${Config.DB_IP}/user/sign-in`, {
  email: email,
  password: password,
}
```

### 이메일 찾기
```jsx
axios.post(`http://${Config.DB_IP}/user/email`, {
  name: name,
  phone: phone,
}
```

### 비밀번호 찾기
```jsx
axios.post(`http://${Config.DB_IP}/password`, {
  email: email,
  newPassword: newPassword,
  name: name,
  phone: phone,
}

**Comment by s-minii** [comment]
확인했습니다!
빠른 시일 내로 테스트 진행합시다 :)

**Comment by thelight0804** [comment]
데이터 처리가 성공했을 때 테스트는 모두 진행했습니다.
데이터 처리에 실패했을 때 예외 처리를 추가해야 할 거 같습니다.

- [ ] 회원가입 할 때 이메일 또는 전화번호가 같다면 중복 예외 처리
- [ ] 로그인 할 때 입력된 값이 다르다면 로그인 실패 예외 처리
- [ ] 이메일 찾기 할 때 입력된 값이 다르다면 이메일 찾기 실패 예외 처리
- [ ] 비밀번호 찾기 할 때 입력된 값이 다르다면 비밀번호 찾기 실패 예외 처리

**Comment by s-minii** [comment]
위 예외 처리들 재작성해서 PR했습니다!

**Comment by thelight0804** [comment]
모든 테스트가 완료되었습니다. 수고하셨습니다!
