### ISSUE TITLE
일반 게시글 조회시, '숨김' 게시글 포함 문제

### ISSUE THREAD

**Issue by s-minii** [thelight0804/subak#45]
일반 게시글 조회시, '숨김' 게시글이 포함되어 조회되는 문제가 발생하고 있어요! 
곧 해결하겠습니다.

그리고 '판매 완료' 게시글은 사용자가 이전에 거래됐던 상품의 가격을 확인할 수 있는 수단으로써 필요하다고 생각했어요. 
그래서 일반 조회시에도 '판매 완료' 게시글은 조회되게 하고, '판매 완료 게시글 제외' 라는 기능을 추가로 구현하는 것이 좋아보여요!

**Comment by thelight0804** [comment]
판매 내역 페이지 안에 필터를 통해서 판매 완료를 보이게 또는 제외하게 만들면 되겠군요

**Comment by s-minii** [comment]
메인페이지 조회시, '숨김' 게시글이 포함되어 조회되는 문제 해결했습니다!

**Comment by s-minii** [comment]
현재 당근마켓에서는 검색 기능 사용 후에, '거래 가능만 보기' 라는 토글로 '판매 완료' 게시글을 제어합니다. 
(기본값: 거래가능만 보기 -> 판매 완료 게시글은 안 본다.)
 
그래서 검색 기능 개발 후에, 추가로 개발하겠습니다!

**Comment by s-minii** [comment]
검색기능 및 '거래 가능만 보기' 토글 구현완료했습니다!
