### ISSUE TITLE
구매 & 판매 단계 구상

### ISSUE THREAD

**Issue by thelight0804** [thelight0804/subak#64]
구매하기 & 판매하기 단계에서 의견이 있어서 남깁니다.

## 현재 구상

> **지금까지는 판매자를 기준으로 개발을 진행했습니다.**

1. 판매자가 댓글을 선택합니다
2. 해당되는 댓글의 유저에게 '판매하기' 버튼을 클릭합니다
3. 게시물에 대한 물건이 판매됩니다

## 새로운 구상

> **판매자가 아닌 구매자를 기준으로 합니다.**

1. 구매자가 게시물을 선택합니다
2. 해당되는 게시물에 '구매하기' 버튼을 클릭합니다
3. 구매자의 ID가 게시글에 전달되면서 물건이 판매됩니다.

이렇게 판매자가 아니라 구매자를 기준으로 물건 거래가 이루어져야 한다고 생각합니다.
해당 구상에 있어서 회의가 필요해 보입니다.

**Comment by s-minii** [comment]
확인하였습니다!
20시 회의에서 이야기 해봅시다!

**Comment by s-minii** [comment]
반영했습니다!
